boeunbox/config/urls.py
from django.contrib import admin
from django.urls import path, include

from mainapp.views import index, terms, privacy
from cscenterapp import views
from myboeunapp.views import myboeun
from productapp.views import product
from subscrapp.views import subscr

from django.conf import settings
from django.conf.urls.static import static
from django_summernote.widgets import SummernoteWidget

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('terms-of-use/', terms, name='terms'),
    path('privacy-policy/', privacy, name='privacy'),
    path('productapp/', include('productapp.urls')),
    path('subscr/', subscr, name="subscr"),
    path('signupapp/', include('signupapp.urls')),
    path('cscenterapp/', include('cscenterapp.urls')),
    path('myboeun/', include('myboeunapp.urls')),
    path('accounts/', include('allauth.urls')),
    path('summernote/', include('django_summernote.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boeunbox/cscenterapp/urls.py
from django.urls import path
from .views import cscenter,create, update, detail,delete,create_comment,enquiry, modify
from cscenterapp import views

app_name = 'cscenterapp'
urlpatterns = [
    path('create/', views.create, name="create"),
    path('cscenter/', views.cscenter, name="cscenter"),
    path('detail/<int:detail_id>', views.detail, name="detail"),
    path('update/<int:update_id>', views.update, name="update"),
    path('delete/<int:delete_id>', views.delete, name="delete"),
    path('enquiry/', views.enquiry, name="enquiry"),
    path('modify/', views.modify, name="modify"),
]

boeunbox/mainapp/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'index.html')

def terms(request):
    return render(request, 'terms-of-use.html')

def privacy(request):
    return render(request, 'privacy-policy.html')

boeunbox/mainapp/templates/base.html
{%load static%}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        보은박스
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="shortcut icon" href="{% static 'image/favicon.ico' %}" />
    <link rel="icon" href="{% static 'image/favicon.ico' %}" />
    <!-- Font Awesome icons -->
    <script src="https://kit.fontawesome.com/0b88962ca7.js" crossorigin="anonymous"></script>
    <!-- 눈누 웹폰트 '마포꽃섬' -->
    <style>
        @font-face {
            font-family: 'MapoGoldenPier';
            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2001@1.1/MapoGoldenPierA.woff') format('woff');
            font-weight: normal;
            font-style: normal;
        }

        * {
            font-family: MapoGoldenPier;
        }
    </style>
    {% block extrahead %}
    {%endblock%}
</head>

<body>
    <!-- NAV BAR 1063px 이상 -->
    <nav class="navbar fixed-top" id="id_nav">
        <div class="navbar-logo">
            <a href="{% url 'index' %}"><i class="fas fa-gift"></i>&nbsp;보은박스</a>
        </div>
        <div class="navbar-container">
            <ul class="navbar-list">
                <li><a href="{% url 'subscr' %}">보은 시작하기</a></li>
                <li><a href="{% url 'product' %}">전체 상품 보기</a></li>
                <li><a href="{% url 'cscenterapp:cscenter' %}">고객센터</a></li>
                <li><a href="{% url 'myboeun' %}">나의 보은</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}">로그아웃</a></li>
                {% else %}
                <li><a href="{% url 'login' %}">로그인/회원가입</a></li>
                {% endif %}
            </ul>
        </div>
        <button class="btn-sidebar" id="myBtn" onclick="myFunction()"><i class="fas fa-bars"></i></button>
    </nav>
    <!-- NAV BAR 1063px 미만 -->
    <nav class="modal-navbar" id="modal_nav">
        <div class="modal-sidebar" id="mySidebar">
            <button class="btn-exit" onclick="myFunction()"><i class="fas fa-times"></i></button>
            <ul class="modal-list">
                <li><a href="{% url 'subscr' %}">보은 시작하기</a></li>
                <li><a href="{% url 'product' %}">전체 상품 보기</a></li>
                <li><a href="{% url 'cscenterapp:cscenter' %}">고객센터</a></li>
                <li>
                    <button class="myboeun_btn" id="myDropdown" onclick="dropFunction()">나의 보은 <div class="down"><i
                                class="fas fa-caret-down"></i></div>
                        <div class="up"><i class="fas fa-caret-up"></i></div>
                    </button>
                    <ul class="submenu">
                        <li id="submenu_li"><a href="{% url 'myboeun' %}">- 내 구독내역</a></li>
                        <li id="submenu_li"><a href="{% url 'mileage' %}">- 마일리지</a></li>
                        <li id="submenu_li"><a href="{% url 'update' %}">- 회원정보 수정</a></li>
                        <li id="submenu_li"><a href="{% url 'address' %}">- 배송지 관리</a></li>
                        <li id="submenu_li"><a href="{% url 'review' %}">- 리뷰 관리</a></li>
                    </ul>
                </li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}">로그아웃</a></li>
                {% else %}
                <li><a href="{% url 'login' %}">로그인/회원가입</a></li>
                {% endif %}
            </ul>
        </div>
        <div class="overlay" onclick="myFunction()"></div>
    </nav>

    {% block contents %}
    <!-- 페이지별로 다르게 보일 content를 입력하는 block -->
    {% endblock %}

    <!-- 공통 FOOTER -->
    <footer class="footer">
        <div class="copyright">© BOEUNBOX 2020 All rights reserved.</div>
        <div class="terms">
            <div class="terms-content"><a href="{% url 'terms' %}">이용약관</a></div>
            <div class="terms-content"><a href="{% url 'privacy' %}">개인정보 처리방침</a></div>
        </div>
    </footer>

    <!-- 자바스크립트 -->
    <script src="{% static 'js/scripts.js' %}"></script>
</body>

</html>

boeunbox/mainapp/templates/index.html
<!-- 공통 필수 -->
{% extends 'base.html' %}
{% load static %}

<!-- 타이틀 -->
{% block title %}
보은박스 - 메인
{% endblock %}

<!-- head 작성 시작 -->
{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/index.css' %}" />
{% endblock %}

<!-- body 작성 시작 -->
{% block contents %}
<div class="wrap">
    <!-- 섹션1 -->

    <div class="top" id="s1">
        <div class="text-container">
            <p class="top-title">보은박스</p>
            <p class="top-text">보은박스는 마음을 담습니다.</p>
            <button class="btn"><a href="{% url 'product' %}">상자 채우기</a></button>
        </div>
    </div>
    <!-- 섹션2 -->
    <div class="middle" id="s2">
        <div class="text-container">
            <p class="middle-text">매달 내가 바로 곁에서 챙겨드리는 것처럼</p>
            <p class="middle-text">한 달에 한 번 보은박스</p>
            <button class="btn"><a href="{% url 'subscr' %}">구독 시작하기</a></button>
        </div>
    </div>
    <!-- 섹션3 -->
    <div class="bottom" id="s3">
        <div class="text-container">
            <p class="bottom-text">푸른 하늘보다 높고, 푸른 바다보다 넓은 당신의 은혜</p>
            <p class="bottom-text">어떻게 하면 일상 속에서 보답할 수 있을까?</p>
            <p class="bottom-text">마음과 마음을 이어주기 위해서 보은박스가 탄생했습니다.</p>
        </div>
    </div>
</div>

<nav class="sidenav fixed-right">
    <div class="sidenav-container">
        <ul class="sidenav-list">
            <li><a href="#s1"><i class="fas fa-circle"></i></a></li>
            <li><a href="#s2"><i class="fas fa-circle"></i></a></li>
            <li><a href="#s3"><i class="fas fa-circle"></i></a></li>
        </ul>
    </div>
</nav>
{% endblock %}

boeunbox/mainapp/templates/privacy-policy.html
<!-- 공통 필수 -->
{% extends 'base.html' %}
{% load static %}

<!-- 타이틀 -->
{% block title %}
보은박스 - 이용약관
{% endblock %}

<!-- head 작성 시작 -->
{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/privacy-policy.css' %}" />
{% endblock %}

<!-- body 작성 시작 -->
{% block contents %}
<hr id="top-line">
<div class="wrap">
    <div class="content">
        <p class="content-title">개인정보 처리방침</p>
        <p class="content-term">BBTeam(이하 "회사”라 함)은 이용자들의 개인정보보호를 매우 중요시하며, 「정보통신망 이용촉진 및 정보보호 등에 관한 법률」을 준수하고 있습니다. 회사는
            개인정보취급방침을 통하여 고객님께서 제공하시는 개인정보가 어떠한 용도와 방식으로 이용되고 있으며, 개인정보보호를 위해 어떠한 조치가 취해지고 있는지 알려드립니다. 회사는 개인정보취급방침을
            개정하는 경우 웹사이트 공지사항(또는 개별공지)을 통하여 공지할 것입니다.<br><br>
            BBTeam의 개인정보 취급방침은 다음과 같은 내용을 담고 있습니다.
        <ol>
            <li class="content-list">수집하는 개인정보의 항목 및 수집방법</li>
            <li class="content-list">개인정보의 수집 및 이용목적</li>
            <li class="content-list">개인정보의 보유 및 이용기간</li>
            <li class="content-list">개인정보의 파기 절차 및 방법</li>
            <li class="content-list">개인정보의 제3자 제공</li>
            <li class="content-list">개인정보의 취급위탁</li>
            <li class="content-list">이용자 및 법정대리인의 권리와 그 행사방법</li>
            <li class="content-list">쿠키(cookie)의 운영에 관한 사항</li>
            <li class="content-list">개인정보관리책임자 및 담당자의 연락처</li>
            <li class="content-list">고지의 의무</li>
        </ol>
        </p>
        <hr id="content-line">
        <p class="content-article">1. 수집하는 개인정보의 항목 및 수집방법</p>
        <p class="content-term">회사는 회원가입, 비회원 구매, 상담, 불량이용의 방지 등을 위해 아래와 같은 개인정보를 수집하고 있습니다.<br><br>
            - 필수항목 : 이름, ID, 비밀번호, 이메일, 전화번호, 제품사용장소, 배송주소, IP Address, 결제기록(구매물품), 출생연도(나이), 성별<br>
            - 선택항목 : 개인맞춤 서비스를 제공하기 위하여 회사가 필요로 하는 정보</p>
        <p class="content-article">2. 개인정보의 수집 및 이용목적</p>
        <p class="content-term">회사는 수집한 개인정보를 다음의 목적을 위해 활용합니다.<br><br>
            가. 서비스 제공에 관한 계약 이행 및 서비스 제공에 따른 요금정산, 콘텐츠 제공, 구매 및 요금 결제, 물품배송 또는 청구지 등 발송, 금융거래 본인 인증 및 금융서비스<br>
            나. 회원 관리 회원제 서비스 이용에 따른 본인확인, 개인 식별, 불량회원의 부정 이용 방지와 비인가 사용 방지, 가입 의사 확인, 연령확인, 불만처리 등 민원처리, 고지사항 전달<br>
            다. 마케팅 및 광고에 활용 이벤트 등 광고성 정보 전달, 접속 빈도 파악 또는 회원의 서비스 이용에 대한 통계</p>
        <p class="content-article">3. 개인정보의 보유 및 이용기간</p>
        <p class="content-term">회사는 원칙적으로 개인정보 수집 및 이용목적이 달성된 후에는 해당 정보를 지체 없이 파기합니다. 단, 상법 및 「전자상거래등에서의 소비자보호에 관한 법률」 등
            관련 법령의 규정에 의하여 다음과 같이 거래 관련 관리 의무 관계의 확인 등을 이유로 일정기간 보유하여야 할 필요가 있을 경우에는 일정기간 보유합니다.<br><br>
            - 계약 또는 청약철회 등에 관한 기록 : 5년 (전자상거래등에서의 소비자보호에 관한 법률)<br>
            - 대금결제 및 재화 등의 공급에 관한 기록 : 5년 (전자상거래등에서의 소비자보호에 관한 법률)<br>
            - 소비자의 불만 또는 분쟁처리에 관한 기록 : 3년 (전자상거래등에서의 소비자보호에 관한 법률)<br>
            - 설문조사, 이벤트 등 일시적 목적을 위하여 수집한 경우 : 당해 설문조사, 이벤트 등의 종료 시점<br>
            - 본인확인에 관한 기록 : 6개월(정보통신망 이용촉진 및 정보보호 등에 관한 법률)<br>
            - 방문(로그)에 관한 기록 : 3개월(통신비밀보호법)</p>
        <p class="content-article">4. 개인정보의 파기 절차 및 방법</p>
        <p class="content-term">회사는 원칙적으로 개인정보 수집 및 이용목적이 달성된 후에는 해당 정보를 지체없이 파기합니다. 파기절차 및 방법은 다음과 같습니다.<br><br>
            가. 파기절차 : 이용자가 서비스 이용 등을 위해 입력하신 정보는 목적이 달성된 후 별도의 DB로 옮겨져(종이의 경우 별도의 서류함) 내부 방침 및 기타 관련 법령에 의한 정보보호 사유에
            따라(보유 및 이용기간 참조) 일정 기간 저장된 후 파기됩니다. 별도 DB로 옮겨진 개인정보는 법률에 의한 경우가 아니고서는 보유되어지는 이외의 다른 목적으로 이용되지 않습니다.<br>
            나. 파기방법<br>
            - 종이에 출력된 개인정보 : 분쇄기로 분쇄하거나 소각<br>
            - 전자적 파일 형태로 저장된 개인정보 : 기록을 재생할 수 없는 기술적 방법을 사용하여 삭제</p>
        <p class="content-article">5. 개인정보의 제3자 제공</p>
        <p class="content-term">이용자의 개인정보는 개인정보의 수집 및 이용목적에서 동의한 범위 내에서 사용하며, 이용자의 사전 동의 없이는 동 범위를 초과하여 이용하거나 원칙적으로 이용자의
            개인정보를 외부에 공개하지 않습니다. 다만 아래의 경우에는 예외로 합니다.<br><br>
            - 이용자들이 사전에 동의한 경우<br>
            - 법령의 규정에 의거하거나, 수사 목적으로 법령에 정해진 절차와 방법에 따라 수사기관의 요구가 있는 경우</p>
        <p class="content-article">6. 개인정보의 취급위탁</p>
        <p class="content-term">원활한 업무 처리를 위해 이용자의 개인정보를 위탁 처리할 경우 반드시 사전에 개인정보 처리위탁을 받는 자(이하 ‘수탁자’라 합니다)와 개인정보 처리위탁을 하는
            업무의 내용을 고지합니다. 현재 회사의 개인정보처리 수탁자와 그 업무의 내용은 다음과 같습니다.<br><br>
            위탁 대상자(수탁자) : 위탁업무 내용(수탁업무)<br>
            우체국택배 : 상품 배송 업무 및 배송위치 / 도착정보 등의 서비스 제공<br>
            네이버페이 : 네이버페이를 통한 상품 주문 및 배송 등의 서비스 제공<br>
            서울신용평가정보㈜ : 본인인증<br>
            나이스페이 : 결제 PG (간편결제, 신용카드 결제 등)</p>
        <p class="content-article">7. 이용자 및 법정대리인의 권리와 그 행사방법</p>
        <p class="content-term">가. 이용자 및 법정 대리인은 언제든지 등록되어 있는 자신 혹은 당해 만 14세 미만 아동의 개인정보를 조회하거나 수정할 수 있으며 가입해지(동의철회)를
            요청할 수도 있습니다.<br>
            나. 이용자 혹은 만 14세 미만 아동의 개인정보 조회, 수정을 위해서는 "개인정보변경”(또는 "회원정보수정” 등)을, 가입해지(동의철회)를 위해서는 "회원탈퇴"를 클릭하여 본인 확인 절차를
            거치신 후 직접 열람, 정정 또는 탈퇴가 가능합니다.<br>
            다. 혹은 개인정보관리책임자에게 서면, 전화 또는 이메일로 연락하시면 지체 없이 조치하겠습니다.<br>
            라. 이용자가 개인정보의 오류에 대한 정정을 요청하신 경우에는 정정을 완료하기 전까지 당해 개인정보를 이용 또는 제공하지 않습니다. 또한 잘못된 개인정보를 제3자에게 이미 제공한 경우에는 정정
            처리결과를 제3자에게 지체 없이 통지하여 정정이 이루어지도록 하겠습니다.<br>
            마. 회사는 이용자 혹은 법정 대리인의 요청에 의해 해지 또는 삭제된 개인정보는 "3. 개인정보의 보유 및 이용기간"에 명시된 바에 따라 처리하고 그 외의 용도로 열람 또는 이용할 수 없도록
            처리하고 있습니다.</p>
        <p class="content-article">8. 쿠키(cookie)의 운영에 관한 사항</p>
        <p class="content-term">회사는 이용자(접속자)의 정보를 수시로 저장하고 찾아내는 '쿠키(cookie)' 등을 운용합니다. 쿠키란 웹사이트를 운영하는데 이용되는 서버가 귀하의
            브라우저에 보내는 아주 작은 텍스트 파일로서 귀하의 컴퓨터 하드디스크에 저장됩니다. 회사는 다음과 같은 목적을 위해 쿠키를 사용합니다.<br><br>
            가. 쿠키 등 사용 목적 회원과 비회원의 접속빈도나 방문시간 등을 분석, 이용자의 취향과 관심분야를 파악 및 자취 추적, 각종 이벤트 참여 정도 및 방문 회수 파악 등을 통한 타겟마케팅 및 개인
            맞춤 서비스 제공 귀하는 쿠키 설치에 대한 선택권을 가지고 있습니다. 따라서, 귀하는 웹 브라우저에서 옵션을 설정함으로써 모든 쿠키를 허용하거나, 쿠키가 저장될 때마다 확인을 거치거나, 아니면
            모든 쿠키의 저장을 거부할 수도 있습니다.<br>
            나. 쿠키 설정 거부 방법 이용자는 사용하는 웹 브라우저의 옵션을 선택함으로써 모든 쿠키를 허용하거나, 쿠키를 저장할 때마다 확인을 거치거나, 모든 쿠키의 저장을 거부하도록 선택하여 설정할 수
            있습니다.<br>
            - 설정방법 예(인터넷 익스플로어의 경우) : 웹 브라우저 상단의 도구 > 인터넷 옵션 > 개인정보<br>
            - 단, 귀하께서 쿠키 설치를 거부하였을 경우 서비스 제공에 어려움이 있을 수 있습니다.</p>
        <p class="content-article">9. 개인정보보호책임자 및 담당자의 연락처</p>
        <p class="content-term">회사는 고객의 개인정보를 보호하고 개인정보와 관련한 불만을 처리하기 위하여 아래와 같이 관련 부서 및 개인정보보호책임자를 지정하고 있습니다.<br><br>
            가. 귀하께서는 회사의 서비스를 이용하시며 발생하는 모든 개인정보보호 관련 민원을 개인정보보호책임자 로 신고하실 수 있습니다.<br>
            나. 회사는 이용자의 신고사항에 대해 신속하게 충분한 답변을 드릴 것입니다.<br>
            다. 기타 개인정보침해에 대한 신고나 상담이 필요하신 경우에는 아래 기관에 문의하시기 바랍니다.<br>
            개인분쟁조정위원회 (www.1336.or.kr / 1336)<br>
            정보보호마크인증위원회 (www.eprivacy.or.kr / 02-580-0533~4)<br>
            대검찰청 인터넷범죄수사센터 (www.spo.go.kr/site/spo/main.do / 02-3480-3600)<br>
            경찰청 사이버테러대응센터 (www.ctrc.go.kr / 02-392-0330)
        </p>
        <p class="content-article">10. 고지의 의무</p>
        <p class="content-term">현 개인정보취급방침은 2020년 12월 5일부터 적용됩니다. 내용의 추가, 삭제 및 수정이 있을 시에는 개정 최소 7일전부터 홈페이지의 공지사항을 통하여
            고지할 것입니다. 또한 개인정보취급방침에 버전번호 및 개정일자 등을 부여하여 개정여부를 쉽게 알 수 있도록 하고 있습니다. 본 방침은 2020년 12월 5일부터 시행됩니다.</p>
    </div>
</div>
{% endblock %}