boeunbox/config/urls.py
from django.contrib import admin
from django.urls import path, include

from mainapp.views import index, terms, privacy
from cscenterapp import views
from myboeunapp.views import myboeun
from productapp.views import product
from subscrapp.views import subscr

from django.conf import settings
from django.conf.urls.static import static
from django_summernote.widgets import SummernoteWidget

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('terms-of-use/', terms, name='terms'),
    path('privacy-policy/', privacy, name='privacy'),
    path('productapp/', include('productapp.urls')),
    path('subscr/', subscr, name="subscr"),
    path('signupapp/', include('signupapp.urls')),
    path('cscenterapp/', include('cscenterapp.urls')),
    path('myboeun/', include('myboeunapp.urls')),
    path('accounts/', include('allauth.urls')),
    path('summernote/', include('django_summernote.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boeunbox/cscenterapp/urls.py
from django.urls import path
from .views import cscenter,create, update, detail,delete,create_comment,enquiry, modify
from cscenterapp import views

app_name = 'cscenterapp'
urlpatterns = [
    path('create/', views.create, name="create"),
    path('cscenter/', views.cscenter, name="cscenter"),
    path('detail/<int:detail_id>', views.detail, name="detail"),
    path('update/<int:update_id>', views.update, name="update"),
    path('delete/<int:delete_id>', views.delete, name="delete"),
    path('enquiry/', views.enquiry, name="enquiry"),
    path('modify/', views.modify, name="modify"),
]

boeunbox/cscenterapp/models.py
from django.db import models

# Create your models here.
class QNA(models.Model):
    title = models.CharField('',max_length=200)
    desc = models.TextField('')
    writer = models.ForeignKey('signupapp.User', on_delete=models.CASCADE, verbose_name="작성자")
    pic = models.ImageField('사진 첨부', blank=True)
    created_at = models.DateTimeField('생성날짜', auto_now_add=True) #생성될때 픽스됨
    modified_at = models.DateTimeField('수정날짜', auto_now=True)#수정할때마다 바뀜
    
    def __str__(self):
        return self.title

class Comment(models.Model):
    qna = models.ForeignKey(QNA,on_delete=models.CASCADE, null=True, related_name='comment')
    desc = models.CharField('댓글내용',max_length=100)
    created_at = models.DateTimeField('생성날짜', auto_now_add=True)

    def __str__(self):
        return self.desc

boeunbox/cscenterapp/forms.py
from django.forms import ModelForm #Django의 modelform을 쓰기 위해서 import 해주었다.
from .models import QNA, Comment
from django_summernote.widgets import SummernoteWidget

class QNAform(ModelForm):

    class Meta:
        model = QNA
        fields = ('title','desc','pic',)
        widgets = {
            'desc': SummernoteWidget(),
        } 
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].help_text = None
        self.fields['title'].widget.attrs.update({
            'placeholder': "제목을 입력하세요"
        })

class CommentForm(QNAform):

    class Meta:
        model = Comment
        fields = ('desc',)

class UpdateForm(ModelForm):

    class Meta:
        model = QNA
        fields = ('title', 'desc', 'pic',)
        widgets = {
            'desc': SummernoteWidget(),
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].help_text = None
        self.fields['title'].widget.attrs.update({
            'placeholder': "제목을 입력하세요"
        })

boeunbox/cscenterapp/views.py
from django.shortcuts import render,redirect
from .forms import QNAform, CommentForm, UpdateForm
from .models import QNA, Comment
from django.contrib.auth.decorators import login_required
from signupapp.models import User
from django.contrib import auth


# Create your views here.

def cscenter(request):
    return render(request, 'cscenter.html')

@login_required
def enquiry(request):
    context = dict()
    all_QNA = QNA.objects.all().order_by('-id')
    context['all_QNA'] = all_QNA
    return render(request, 'enquiry.html', context)

def create(request):
    context=dict()
    context['QNAform'] = QNAform()
    if request.method == 'POST':
        myform = QNAform(request.POST, request.FILES)
        if myform.is_valid():
            myform.save()
            return redirect('cscenterapp:enquiry')
        else:
            context['QNAform'] = myform
    return render(request,'create.html',context)

def detail(request,detail_id):
    context={}
    one_QNA = QNA.objects.get(id=detail_id) #예를 들면 5번 id 글을 가져오겠다
    
    context['one_QNA'] = one_QNA
    context['comment_form'] = CommentForm

    return render(request, 'detail.html', context)

def modify(request):
    context = {}
    context['updateform'] = UpdateForm()
    if request.method == "POST":
        tempform = UpdateForm(request.POST, request.FILES)
        if tempform.is_valid():
            tempform.save()
            return redirect('index')
        else:
            context['updateform'] = tempform
    return render(request, 'modify.html', context)

def update(request,update_id):
    context={}
    context['updateform'] = UpdateForm(instance=QNA.objects.get(id=update_id))
    
    if request.method=="POST":
        tempform = UpdateForm(request.POST, request.FILES,
                            instance=QNA.objects.get(id=update_id))
        if tempform.is_valid():
            tempform.save()
            return redirect('cscenterapp:detail', update_id)
        else:
            context['updateform'] = tempform
    return render(request, 'modify.html', context)

def delete(request,delete_id):

    one_QNA = QNA.objects.get(id=delete_id)
    one_QNA.delete()
    return redirect('index')

def create_comment(request,QNA_id):
    context = dict()
    if request.method == "POST":
        tmp_comment = CommentForm(request.POST)
        if tmp_comment.is_valid():
            save_comment = tmp_comment.save(commit=False)
            save_comment.QNA = QNA.objects.get(id=QNA_id)
            save_comment.save()
            return redirect('detail', QNA_id)
    return redirect('index')

boeunbox/cscenterapp/templates/create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}

{% endblock %}

{% block contents %}

<h1>1:1문의하기</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{QNAform.as_p}}
    <input type="submit" value="작성">
</form>

{% endblock %}

boeunbox/cscenterapp/templates/cscenter.html
<!-- 공통 필수 -->
{% extends 'base.html' %}
{% load static %}

<!-- 타이틀 -->
{% block title %}
보은박스 - FAQ
{% endblock %}

<!-- head 작성 시작 -->
{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/cscenter.css' %}" />
{% endblock %}

{% block contents %}
<hr id="top_line">
<div class="wrap">
    <div class="content">
        <p class="text-title">자주 묻는 질문</p>
        <div class="accordion">
            <input type="checkbox" id="faq01">
            <label for="faq01">Q. 보은박스는 어떤 서비스인가요?</label>
            <div>
                <div class="text-answer">
                    <p>보은박스는 자주 찾아뵙거나 챙겨드리지 못하는 부모님께 자녀의 마음을 전달할 수 있도록 해주는 정기구독 서비스입니다.
                        <br></br>
                        정기구독으로 부모님께 매달 보은박스를 보내드리고 싶다면 보은 시작하기 페이지에서 정기구독에 대해 알아보세요.
                        <br></br>
                        <a href="{% url 'subscr' %}">보은박스 정기구독 알아보기
                        </a>
                    </p>
                </div>
            </div>
            <input type="checkbox" id="faq02">
            <label for="faq02">Q. 회원가입을 해야만 정기구독이 가능한가요?</label>
            <div>
                <div class="text-answer">
                    <p>구독자 여러분의 정보 보안상의 이유로 보은박스는 매월 정기구독 서비스로 회원가입을 완료해야 서비스 결제도 가능합니다.</p>
                    <br></br>
                    <p>그러므로 정기구독 결제를 원하신다면 반드시 회원가입 절차를 완료해 주시기 바랍니다.</p>
                </div>
            </div>
            <input type="checkbox" id="faq03">
            <label for="faq03">Q. 보은박스의 구성품은 어떻게 되나요?</label>
            <div>
                <div class="text-answer">
                    <p>보은박스의 구성품은 매달 변경됩니다.<br>
                        MD가 직접 고심하여 선정한 보은박스 구성품을 보시려면 전체 상품 보기 페이지를 참조해 주시기 바랍니다.
                        <br></br>
                        <a href="{% url 'product' %}">전체 상품 보기</a>
                    </p>
                </div>
            </div>
            <input type="checkbox" id="faq04">
            <label for="faq04">Q. 보은박스의 구성을 변경할 수 있나요?</label>
            <div>
                <div class="text-answer">
                    <p>보은박스의 구성은 구독하고 계신 서비스 등급에 따라 하트의 총 갯수를 넘지 않는 선에서 변경이 가능합니다.
                        <br></br>
                        이 달의 보은박스 구성을 확인하고 구성 변경을 원하신다면 전체 상품 보기 페이지로 이동하여 하실 수 있습니다.
                        <br></br>
                        <a href="{% url 'product' %}">전체 상품 보기</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="to-enquiry">
            <p class="text-enquiry"><i class="fas fa-caret-right"></i> 찾으시는 사항이 없나요?</p>
            <button class="btn"><a href="{% url 'cscenterapp:enquiry' %}">1:1문의하기</a></button>
        </div>
    </div>
</div>
{% endblock %}

boeunbox/cscenterapp/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
보은박스 - 1:1문의 내용
{% endblock %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/detail.css' %}" />
{% endblock %}

{% block contents %}
<hr id="top_line">
<div class="wrap">
    <div class="container">
        <p class="text-title">1:1문의 내용</p>
        <div class="qna">
            <table class="showtable">
                <thead>
                    <tr>
                        <th scope="col" class="table-head">
                            <p class="qna-title">{{one_QNA.title}}</p>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="table-content">
                            {% autoescape off %}
                            <p class="qna-content">{{one_QNA.desc}}</p>
                            {% endautoescape %}
                        </td>
                    </tr>
                </tbody>
            </table>
            <a href="{% url 'cscenterapp:update' one_QNA.id %}"><button class="qna-btn">내용수정</button></a>
            <a href="{% url 'cscenterapp:delete' one_QNA.id %}"><button class="qna-btn">문의삭제</button></a>
            <a href="{% url 'cscenterapp:enquiry' %}"><button class="qna-btn">목록</button></a>
        </div>
    </div>
</div>

{%endblock%}

boeunbox/cscenterapp/templates/enquiry.html
<!-- 공통 필수 -->
{% extends 'base.html' %}
{% load static %}

<!-- 타이틀 -->
{% block title %}
보은박스 - 1:1문의
{% endblock %}

<!-- head 작성 시작 -->
{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/enquiry.css' %}" />
{% endblock %}

{% block contents %}
<hr id="top_line">
<div class="wrap">
    <div class="content">
        <p class="text-title">1:1 문의하기</p>
        <div class="table-board">
            <table class="qnatable">
                <thead>
                    <tr class="qna-head">
                        <th scope="col">#</th>
                        <th scope="col">제목</th>
                        <th scope="col">작성일</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in all_QNA %}
                    <tr class="qna-body">
                        <th scope="row">{{ i.id }}</th>
                        <td class="line"><a href="{% url 'cscenterapp:detail' i.id %}">
                                <p>{{i.title}}</p>
                            </a></td>
                        <td class="line">{{ i.created_at }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <button class="btn"><a href="{% url 'cscenterapp:create' %}">글쓰기</a></button>
    </div>
</div>
{% endblock %}

boeunbox/cscenterapp/templates/modify.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
보은박스 - 1:1문의 수정
{% endblock %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/modify.css' %}" />
{% endblock %}

{% block contents %}
<hr id="top_line">
<div class="wrap">
    <div class="container">
        <p class="text-title">1:1문의 수정</p>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{updateform.as_p}}
            <button type="submit" class="submitbtn">수정완료</button>
        </form>
    </div>
</div>
{% endblock %}